### ISSUE TITLE
Customizer and Boardcustomizer: PHP Exception

### ISSUE THREAD

**Issue by Tuxdiver** [BlueTeck/kanboard_plugin_boardcustomizer#8]
I am not sure, if it is Boardcustomizers fault, but when I activate the plugin, the "Customizer" page in settings from "Customizer" does not work anymore:

```[Tue Jan 24 14:11:39.459984 2023] [php7:error] [pid 5077] [client 192.168.253.2:53557] PHP Fatal error:  Uncaught Error: Call to undefined method Kanboard\\Plugin\\Boardcustomizer\\Helper\\DynamicAvatar::getUser() in DIRECTORY/kanboard-1.2.26/plugins/Customizer/Template/file/show.php:134\nStack trace:\n#0 DIRECTORY/kanboard-1.2.26/app/Core/Template.php(83): include()\n#1 DIRECTORY/kanboard-1.2.26/app/Helper/LayoutHelper.php(207): Kanboard\\Core\\Template->render()\n#2 DIRECTORY/kanboard-1.2.26/app/Helper/LayoutHelper.php(129): Kanboard\\Helper\\LayoutHelper->subLayout()\n#3 DIRECTORY/kanboard-1.2.26/plugins/Customizer/Controller/CustomizerFileController.php(104): Kanboard\\Helper\\LayoutHelper->config()\n#4 DIRECTORY/kanboard-1.2.26/app/Core/Controller/Runner.php(77): Kanboard\\Plugin\\Customizer\\Controller\\CustomizerFileController->show()\n#5 DIRECTORY/kanboard-1.2.26/app/Core/Controller/Runner.php(31): Kanboard\\Core\\Controller\\Runner->executeController()\n#6 DIRECTORY in DIRECTORY/kanboard-1.2.26/plugins/Customizer/Template/file/show.php on line 134```

The server looks for DynamicAvatar::getUser() in the "Boardcustomer/Helper" code and fails.

- Version: 1.2.26
- PHP Version: 7.4.33
- PHP SAPI: apache2handler

Plugins:
- Customizer: 1.14.0
- Boardcustomizer: 1.1.0
- Moon 1.4.6

We have an older installation, which works:
- Version: 1.2.22
- PHP Version: 7.4.33
- PHP SAPI: apache2handler
- Customizer 1.13.8
- Boardcustomizer: 1.1.0
- Moon 1.4.6

So I am not sure, I you have to fix something oder "customizer" has to...

**Comment by creecros** [comment]
Copy the latest DynamicAvatar.php in Customizer, the one here is out of date.
